//! **FORMULA-PIN** (honest label, NOT a live code oracle) of the spherical
//! (Marshel et al. 2012) display correction. The reference is
//! `MonitorSetup.Monitor.remap()` — `deg = (180/π)·atan(coord/dis)` — which exists
//! ONLY in the deprecated **py2** `retinotopic_mapping` copy (NeuroAnalysisTools
//! 3.1.0 has no `MonitorSetup`). **Irreducible gap:** that py2 module cannot be
//! imported/executed in the locked py3 oracle env without a 2to3 shim, and shims
//! are forbidden — so there is no runnable reference to call. This therefore pins
//! the *published Marshel-2012 arctan formula* (algebraically identical to our
//! `uv_to_angle`), labelled as a formula-pin with the gap stated, NOT dressed as a
//! live oracle. Backed by `gen_spherical_marshel_golden.py` (a formula generator).
//!
//! Our `DisplayGeometry::uv_to_angle` (Spherical) computes
//!   `az = atan(y_cm / xo)`, `el = asin(z_cm / sqrt(xo² + y_cm² + z_cm²))`,
//! which is algebraically the Allen kernel
//!   `deg_x = atan(x_cm / dis)`, `deg_y = atan(y_cm / sqrt(dis² + x_cm²))`
//! (since `asin(z/√(d²+z²)) == atan(z/d)` for `d = √(xo²+y²)`). This pins it
//! numerically against the real Allen formula, not just a round-trip.
//!
//! Fixtures (generated by `gen_spherical_marshel_golden.py`) live under the
//! isi-analysis crate's golden fixtures dir; cm = (horizontal, vertical) in cm,
//! deg = (azimuth, elevation) in degrees, meta = [DIS, W_cm, H_cm, N]. The rig
//! pose is centred (no azimuth/elevation/bisector offset) so the cm↔uv map is
//! `u = 0.5 + x/W`, `v = 0.5 − y/H`.

use openisi_stimulus::geometry::{DisplayGeometry, ProjectionType};

fn load_f64(bytes: &[u8]) -> Vec<f64> {
    bytes
        .chunks_exact(8)
        .map(|c| f64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

#[test]
fn spherical_matches_allen_marshel_remap() {
    let cm = load_f64(include_bytes!(
        "../../isi-analysis/tests/golden/fixtures/sph_marshel_cm.bin"
    ));
    let deg = load_f64(include_bytes!(
        "../../isi-analysis/tests/golden/fixtures/sph_marshel_deg.bin"
    ));
    let meta = load_f64(include_bytes!(
        "../../isi-analysis/tests/golden/fixtures/sph_marshel_meta.bin"
    ));
    let (dis, w_cm, h_cm, n) = (meta[0], meta[1], meta[2], meta[3] as usize);

    // Centred rig pose: no angular/bisector offsets, so cm maps linearly to uv.
    let geom = DisplayGeometry::new(
        ProjectionType::Spherical,
        dis,
        0.0,
        0.0,
        0.0,
        0.0,
        w_cm,
        h_cm,
        1920,
        1080,
    );

    let mut max_az = 0.0f64;
    let mut max_el = 0.0f64;
    for i in 0..n {
        let (x_cm, y_cm) = (cm[2 * i], cm[2 * i + 1]);
        let u = 0.5 + x_cm / w_cm;
        let v = 0.5 - y_cm / h_cm;
        let (az, el) = geom.uv_to_angle(u, v);
        max_az = max_az.max((az - deg[2 * i]).abs());
        max_el = max_el.max((el - deg[2 * i + 1]).abs());
    }
    eprintln!("spherical Marshel vs Allen remap: max az diff = {max_az:.2e} deg, max el diff = {max_el:.2e} deg");
    assert!(
        max_az < 1e-9 && max_el < 1e-9,
        "spherical correction diverges from Allen Marshel remap: az {max_az:.2e}, el {max_el:.2e}"
    );
}
