//! **FORMULA-PIN** (honest label, NOT a live code oracle) of the spherical
//! (Marshel et al. 2012) display correction. The reference is
//! `MonitorSetup.Monitor.remap()` — `deg = (180/π)·atan(coord/dis)` — which lives
//! only in the **py2** `retinotopic_mapping` / `corticalmapping` copies
//! (NeuroAnalysisTools 3.1.0 has no `MonitorSetup`). **Irreducible gap, empirically
//! verified:** importing `retinotopic_mapping.MonitorSetup` in the locked py3.9
//! oracle env raises `SyntaxError` — its import chain hits `tools/ImageAnalysis.py`
//! line 14 `print e` (a py2 print statement), and `MonitorSetup.py` itself uses
//! `xrange`. So the module cannot be imported/executed without a 2to3 shim, and
//! shims are forbidden — there is no runnable reference to call. This therefore pins
//! the *published Marshel-2012 arctan formula* (algebraically identical to our
//! `uv_to_angle`), labelled as a formula-pin with the gap stated, NOT dressed as a
//! live oracle. Backed by `gen_spherical_marshel_golden.py` (a formula generator).
//!
//! Our `DisplayGeometry::uv_to_angle` (Spherical) computes
//!   `az = atan(y_cm / xo)`, `el = asin(z_cm / sqrt(xo² + y_cm² + z_cm²))`,
//! which is algebraically the Allen kernel
//!   `deg_x = atan(x_cm / dis)`, `deg_y = atan(y_cm / sqrt(dis² + x_cm²))`
//! (since `asin(z/√(d²+z²)) == atan(z/d)` for `d = √(xo²+y²)`). This pins it
//! numerically against the real Allen formula, not just a round-trip.
//!
//! Fixtures (generated by `gen_spherical_marshel_golden.py`) live under the
//! isi-analysis crate's golden fixtures dir; cm = (horizontal, vertical) in cm,
//! deg = (azimuth, elevation) in degrees, meta = [DIS, W_cm, H_cm, N]. The rig
//! pose is centred (no azimuth/elevation/bisector offset) so the cm↔uv map is
//! `u = 0.5 + x/W`, `v = 0.5 − y/H`.

use agreement::{Eps, Tol};
use openisi_stimulus::geometry::{DisplayGeometry, ProjectionType};

/// Load an `f64` `.npy` fixture (self-describing dtype + shape) as a flat `Vec`.
/// The dtype is verified on load.
fn load_f64(bytes: &[u8]) -> Vec<f64> {
    npyz::NpyFile::new(std::io::Cursor::new(bytes))
        .expect("parse .npy fixture")
        .into_vec::<f64>()
        .expect("read .npy fixture as f64 (dtype mismatch?)")
}

#[test]
fn spherical_matches_allen_marshel_remap() {
    let cm = load_f64(include_bytes!(
        "../../isi-analysis/tests/golden/fixtures/sph_marshel_cm.npy"
    ));
    let deg = load_f64(include_bytes!(
        "../../isi-analysis/tests/golden/fixtures/sph_marshel_deg.npy"
    ));
    let meta = load_f64(include_bytes!(
        "../../isi-analysis/tests/golden/fixtures/sph_marshel_meta.npy"
    ));
    let (dis, w_cm, h_cm, n) = (meta[0], meta[1], meta[2], meta[3] as usize);

    // Centred rig pose: no angular/bisector offsets, so cm maps linearly to uv.
    let geom = DisplayGeometry::new(
        ProjectionType::Spherical,
        dis,
        0.0,
        0.0,
        0.0,
        0.0,
        w_cm,
        h_cm,
        1920,
        1080,
    );

    let mut ours: Vec<f64> = Vec::with_capacity(2 * n);
    for i in 0..n {
        let (x_cm, y_cm) = (cm[2 * i], cm[2 * i + 1]);
        let u = 0.5 + x_cm / w_cm;
        let v = 0.5 - y_cm / h_cm;
        let (az, el) = geom.uv_to_angle(u, v);
        ours.push(az);
        ours.push(el);
    }
    // az/el (degrees) cross zero → ABSOLUTE ε bound, through the project's single
    // grounded comparator. The Marshel-2012 arctan is algebraically identical to
    // `uv_to_angle` (asin↔atan), so the only difference is f64 rounding. MEASURED
    // worst ≈ 7.11e-15 ≈ 32·ε_f64 (elevation) ⇒ K=64 (was a magic `1e-9`).
    let reference = &deg[..2 * n];
    let tol = Tol::abs(64, Eps::F64);
    let d = tol.check(&ours, reference);
    eprintln!("spherical Marshel vs Allen remap: max_abs={:.3e} deg ({n} pts)", d.max_abs);
    tol.assert("spherical correction vs Allen Marshel remap", &ours, reference);
}
